### ISSUE TITLE
nvue 拦截问题 0.0.x生效  1.0.x版本不生效

### ISSUE THREAD

**Issue by Songwaitter** [devilwjp/uni-crazy-router#14]
经测试纯nvue项目，1.0.x版本。
afterEach不生效，拦截了页面，跳转后无法返回。
使用0.0.x版本正常

**Comment by devilwjp** [comment]
@Songwaitter nvue有一些已知问题，暂时未解决

**Comment by Songwaitter** [comment]
使用0.0.31版本正常

**Comment by devilwjp** [comment]
@Songwaitter 那就是bug

**Comment by devilwjp** [comment]
@Songwaitter 最好提供一个示例项目

**Comment by Songwaitter** [comment]
[test.zip](https://github.com/devilwjp/uni-crazy-router/files/8549305/test.zip)

**Comment by devilwjp** [comment]
@Songwaitter 试试1.1.0
