### ISSUE TITLE
regenerator-runtime问题

### ISSUE THREAD

**Issue by itmanyong** [devilwjp/uni-crazy-router#15]
使用[uniapp npx命令](https://uniapp.dcloud.io/quickstart-cli.html#install-vue-cli)创建的vue3+vite模板
并使用一下代码注册:
![image](https://user-images.githubusercontent.com/53500371/177187424-fd35c3e4-5e89-48b5-9028-692bbe5a293e.png)
遗憾的是只要运行就会报以下错误
![image](https://user-images.githubusercontent.com/53500371/177187538-63babeb6-f51c-4069-a997-14894be159d7.png)
尝试过build.rollupOptions.external配置以及额外安装"regenerator-runtime包。也会在构建成功之后在微信开发者工具上报错""regenerator-runtime not is undefined".

**Comment by devilwjp** [comment]
@itmanyong 手动安装下

**Comment by devilwjp** [comment]
@itmanyong 
可以先尝试一下我提供的vue3的测试项目，也是通过uniapp vue-cli安装的，你可以直接clone进行安装，再一下
https://github.com/devilwjp/uni-crazy-router-example

**Comment by devilwjp** [comment]
![image](https://user-images.githubusercontent.com/38802722/177191794-30fcb4ef-7963-4d28-84af-d5d437f26dc5.png)

**Comment by devilwjp** [comment]
@itmanyong 然后对比一下我的项目和你的项目uniapp的版本是否有区别

**Comment by devilwjp** [comment]
@itmanyong 
我使用`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`安装的新的vue3项目，然后安装uni-crazy-router，依旧可以正常运行

**Comment by itmanyong** [comment]
> @itmanyong 我使用`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`安装的新的vue3项目，然后安装uni-crazy-router，依旧可以正常运行

我尝试了将你提供的示例down下来后进行运行，还是一样的报错，如下图，会不会是包管理器的问题，我down下来后直接pnpm i 进行安装然后运行
![image](https://user-images.githubusercontent.com/53500371/177367586-ac928702-054f-4e44-bade-40cef8c60ec2.png)

**Comment by devilwjp** [comment]
@itmanyong 嗯，可能是pnpm的问题，你尝试使用yarn或者npm安装试下

**Comment by itmanyong** [comment]
@devilwjp 就是pnpm的原因，期待兼容~-~

**Comment by devilwjp** [comment]
@itmanyong 这个是pnmp的包管理问题，其他很多项目都遇到了用pnmp安装vue3项目后，缺少regenerator-runtime依赖的问题

**Comment by devilwjp** [comment]
@itmanyong 可以尝试使用pnpm官方提供的[解决方案](https://pnpm.io/faq#solution-3)

**Comment by itmanyong** [comment]
@devilwjp 好的！感谢解答！哎！感觉pnpm对于这个问题也是很棘手，一直没处理
