### ISSUE TITLE
路由拦截报错：beforeEach中没有使用next、动作被拦截，因为已经有一个正在执行的路由动作

### ISSUE THREAD

**Issue by Cowjiang** [devilwjp/uni-crazy-router#17]
```
uniCrazyRouter.beforeEach( async (to, from, next) => {
    if (!allowList.includes(to.url)) {
        uniCrazyRouter.afterNotNext(() => {
            uni.navigateTo({
                url: '/pages/login/login'
            })
        })
        return
    }
    next()
})
```
![image](https://user-images.githubusercontent.com/57822554/180599301-6377b423-5704-4902-b45d-70be6cc6ea48.png)

**Comment by Cowjiang** [comment]
版本号：1.1.1
vite、vue3.2
小程序平台

**Comment by devilwjp** [comment]
@Cowjiang 
方便提供一个问题复现的示例项目吗？

**Comment by devilwjp** [comment]
@Cowjiang 第一个错误属于正常，第二个错误是afterNotNext中的navigateTo的返回，还是其他地方的跳转的返回？我看你afterNotNext中的navigateTo并没有打印返回

**Comment by Cowjiang** [comment]
> 

我自己封装了一个跳转的公用方法，第二个错误就是navigateTo的fail，我在上述示例代码替换成uni的navigateTo而已
