### ISSUE TITLE
路由拦截时问号后面的参数丢失的建议

### ISSUE THREAD

**Issue by MigoNoSalt** [devilwjp/uni-crazy-router#2]
#### 原code.js[174行]
toUrl = url.resolve(currentUrl,payload.url).replace(/^\/([^\/])/,'$1')**.replace(/([^?]+)\?[\s\S]*/,'$1')**

#### 原core.js[165行-182行]
let passedParams = {}
if (jumpType === 'navigateBack') {
	let {
		delta = 1
	} = payload
	let targetIndex = getCurrentPages().length - 1 - delta
	if (targetIndex < 0) {
		targetIndex = 0
	}
	toUrl = getCurrentPages()[targetIndex].route
} else {
	// 去除根斜杠
	let tempUrl = url.resolve(currentUrl, payload.url).replace(/^\/([^\/])/, '$1')
	//console.log('tempUrl:', tempUrl)
	toUrl = tempUrl.replace(/([^?]+)\?[\s\S]*/, '$1')
	//console.log('toUrl:', toUrl)
	let toQuery = tempUrl.replace(/(.*?)\?([^?]+)*/, '$2')
	//console.log('toQuery:', toQuery)
	if (toQuery) {
		passedParams = passedParams || {}
		try{
			let query = toQuery.trim().split('&')
			for (let i = 0; i < query.length; i++) {
				let kv = query[i].split('=')
				passedParams[kv[0]] = kv[1]
			}
			//console.log('passedParams:', passedParams)
		} catch(e) {
			console.warn("无效的URL参数：" + tempUrl)
		}
	}
}

passedParams = Object.assign(passedParams, payload.passedParams || {})
let to = routerStatus.to = {
	url: toUrl,
	routeParams: payload.routeParams,
	passedParams,
	jumpType
}

**Comment by devilwjp** [comment]
请指明什么环境，174行的代码toUrl并不会作为最终的跳转地址被用到navigateTo中，你是希望原生的url地址的参数在beforeEach和afterEach中被显示出来吗？如果是的话，我将加在query属性中

**Comment by MigoNoSalt** [comment]
我的场景是需要在路由拦截时获取到url中的参数，
uniCrazyRouter.beforeEach(async (to, from, next) => {
...此处获取to中的参数	
})
而您定义的对象中已对toUrl做了截取，并且未处理问号后的参数，导致在uniCrazyRouter的钩子函数中无法获取到那部分参数
let to = routerStatus.to = {
        url: toUrl,
        routeParams: payload.routeParams,
        passedParams: payload.passedParams,
        jumpType
    }

**Comment by devilwjp** [comment]
嗯，理解了，我在之后的版本会放在to和from的query属性中，并对值进行decodeURIComponent的处理。

**Comment by MigoNoSalt** [comment]
> 嗯，理解了，我在之后的版本会放在to和from的query属性中，并对值进行decodeURIComponent的处理。

多谢大佬

**Comment by devilwjp** [comment]
@MigoNoSalt 已更新，请升级到0.0.18版本
