### ISSUE TITLE
初次进入时没有拦截,只有使用了uni 提供页面跳转之后才能起到相应的作用

### ISSUE THREAD

**Issue by ZhiGang-Fang** [devilwjp/uni-crazy-router#3]
初次进入时没有拦截,只有使用了uni 提供页面跳转之后才能起到相应的作用,默认进入没有任何作用,希望是只要进入页面了,都会触发拦截操作

**Comment by devilwjp** [comment]
@ZhiGang-Fang 不好意思，才看到这个issue，初次进入是没有办法拦截的，因为至少要有一个页面展示，并且初次进入属于原生方式，我在文档里也有说明一些原生方式是无法拦截的，但是可以触发afterEach，可以在afterEach里进行跳转，变向的做到拦截作用，因为是跨端框架的router，所以希望做到表现统一，其实在h5下是可以做到初次进入拦截的，希望我的解答你能满意，如果满意请回复一下，我再关闭这个issue

**Comment by ZhiGang-Fang** [comment]
谢谢
