### ISSUE TITLE
为什么navigator组件产生的跳转不算主动跳转呢？

### ISSUE THREAD

**Issue by terranc** [devilwjp/uni-crazy-router#31]

**Comment by devilwjp** [comment]
@terranc 只对uni的api产生影响

**Comment by terranc** [comment]
但这在团队协作中会很容易发生问题，其它人看到拦截器肯定会认为页面跳转都会触发，如果是启动不会触发还能理解，但navigator组件不会触发，就。。。并且如果不用navigator的页面链接应该用的组件呢？

**Comment by devilwjp** [comment]
建议自己包装navigator组件，替换uni的组件

**Comment by terranc** [comment]
ok
