### ISSUE TITLE
建议 navigateTo方法可以加个 query 参数

### ISSUE THREAD

**Issue by leitingx762** [devilwjp/uni-crazy-router#9]
有时候会需要持久化参数，建议navigateTo方法可以加个query参数，qs 序列化一下拼到url上，方便下个页面使用（确实是我想偷懒。。。。）

**Comment by devilwjp** [comment]
@leitingx762 我想了解一下你的需求场景，你是否只需要在下个页面获取到参数即可？如果只需要在下个页面获取到参数，那么可以使用routerParams，因为我并不想污染uni自身的方法使用方式，所以添加了新的序列化参数名称  
````javascript
uni.navigateTo({
    url: '/pages/test/test?a=1&b=1', // 不影响原生的参数传递
    // 提供了基于页面级别的路由参数对象
    routeParams: {
        c:1,
        d:1
    },
    // 提供了基于跳转过程的过程参数对象
    passedParams: {
        e:1,
        f:1
    }
})
````  
在下个页面里获取可以使用`this.$routeParams`和`this.$passedParams`  
routeParams和passedParams是新的参数和功能，不影响uni原生的url级别的参数

**Comment by leitingx762** [comment]
> @leitingx762 我想了解一下你的需求场景，你是否只需要在下个页面获取到参数即可？如果只需要在下个页面获取到参数，那么可以使用routerParams，因为我并不想污染uni自身的方法使用方式，所以添加了新的序列化参数名称
> 
> ```js
> uni.navigateTo({
>     url: '/pages/test/test?a=1&b=1', // 不影响原生的参数传递
>     // 提供了基于页面级别的路由参数对象
>     routeParams: {
>         c:1,
>         d:1
>     },
>     // 提供了基于跳转过程的过程参数对象
>     passedParams: {
>         e:1,
>         f:1
>     }
> })
> ```
> 
> 在下个页面里获取可以使用`this.$routeParams`和`this.$passedParams`
> routeParams和passedParams是新的参数和功能，不影响uni原生的url级别的参数
> routeParams是根据路由级别持久化的参数
> passedParams是非持久化的过程级别的参数

重新理解了下路由级持久, 由于小程序没有刷新页面功能, 用 routeParms可以满足场景. 谢谢大佬~
最初是考虑到刷新的情况和想传参时可以偷个懒,才提的这个issues_(:3」∠)_
